### ISSUE TITLE
Update published version

### ISSUE THREAD

**Issue by josago97** [tryphotino/PhotinoSamples.VSExtension#7]
The extension was last published in October 2022. It would need to be updated to make the Blazor template available.

**Comment by MikeYeager** [comment]
@josago97 All of the Blazor templates now live in the Photino.Blazor project. They became too difficult to maintain separately. I don't think we will make project templates out of those going forward. The easiest way to use them is to clone the Photino.Blazor repo, and make a copy of the sample to start your new project.

**Comment by josago97** [comment]
Ok, I understand the decision, but I think it would be better as I mentioned [here](#8). Create a repository with the source code for the templates so that the community can easily improve and update them. Also, I think that it is actually more convenient to have the templates in Visual Studio and create the project using them instead of having to go to the repository, download the example project and modify it.

**Comment by MikeYeager** [comment]
@josago97 All of the project templates are created from the samples which you can download here https://github.com/[tryphotino/photino.Samples](https://github.com/tryphotino/photino.Samples)
